### ISSUE TITLE
Request to change color of mHeaderControl Icon in toolbar

### ISSUE THREAD

**Issue by bit-blit** [maheee/mHeaderControl#2]
I'm using the "compact dark theme" which is one of the three standard themes that are in a stock Firefox install (there is also compact light and default.) Since mHeaderControl uses black for the color of it's toolbar icon, it is barely visible when using the stock "compact dark theme". Any thoughts on changing the color, even if it is some shade of grey? (or whatever you feel would be best) - it would make it much more visible and stand out better in the toolbar. Please consider this. Thanks! Brilliant add-on!

**Comment by maheee** [comment]
Thanks for the input, I'll think of something.
Don't especially like the current icon anyway 😉

**Comment by bit-blit** [comment]
MANY Thanks! Keep up the great work on this GREAT add-on!
